language: swift
osx_image: xcode11.4
git:
  depth: false # To enable build numbering from an accurate commit count
cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew/
    - /usr/local/lib/mint/
install:
  - bundle install
  - brew update && brew install mint
  - pod repo update
before_script:
  # Prepare a GitHub login to enable the certificates repository to be cloned
  - echo -e "machine github.com\n  login AndrewBennet\n  password $GITHUB_TOKEN" > ~/.netrc
  - bundle exec fastlane preprocess
script:
  - bundle exec fastlane ci || travis_terminate 1;
deploy:
  skip_cleanup: true
  provider: script
  script:
    - bundle exec fastlane upload_build
  on:
    branch: master
after_deploy:
  - bundle exec fastlane tag_build
