language: swift
osx_image: xcode10.1
# To enable build numbering from commit count
git:
  depth: false
before_cache: brew cleanup
cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew/
    - /usr/local/lib/mint/
install: ./build/install.sh
before_script: ./build/preprocess.sh
script:
  - bundle exec fastlane test
deploy:
  #skip_cleanup: true
  provider: script
  script:
    - bundle exec fastlane deploy
  on:
    branch: master