language: swift
osx_image: xcode10.1
git:
  # To enable build numbering from commit count
  depth: false
env:
  matrix:
    - TEST_SDK=platform=iOS Simulator,name=iPhone 7,OS=10.3.1
    - TEST_SDK=platform=iOS Simulator,name=iPhone 8,OS=11.4
    - TEST_SDK=platform=iOS Simulator,name=iPhone XS,OS=12.1
    - TEST_SDK=platform=iOS Simulator,name=iPad Pro (10.5-inch),OS=11.4
before_cache:
 - brew cleanup
cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/lib/mint/
before_install:
  - ./build/before_install.sh
script:
  - ./build/travis.sh
