language: swift
osx_image: xcode10.1
git:
  # To enable build numbering from commit count
  depth: false
before_cache:
 - brew cleanup
cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/lib/mint/
install:
  - brew install mint
  - mint run yonaskolb/xcodegen
  - pod repo update
  - pod install
before_script:
  - ./build/before_install.sh
script:
  - set -o pipefail && xcodebuild -workspace ReadingList.xcworkspace -scheme ReadingList \
      -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3.1" \
      -destination "platform=iOS Simulator,name=iPhone XS,OS=12.1" \
      -destination "platform=iOS Simulator,name=iPad Pro (10.5-inch),OS=11.4" \
      clean test
deploy:
  provider: script
  script: bundle exec fastlane deploy
  on:
    branch: master