language: swift
osx_image: xcode10.1
git:
  # To enable build numbering from commit count
  depth: false
before_cache: brew cleanup
cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/lib/mint/
install: ./build/install.sh
before_script: ./build/preprocess.sh
jobs:
  include:
    - stage: test
      script: fastlane scan --scheme "ReadingList" --device "iPhone 7 (iOS 10.3.1)"
    - script: fastlane scan --scheme "ReadingList" --device "iPhone 8 (iOS 11.4)"
    - script: fastlane scan --scheme "ReadingList" --device "iPhone XS (iOS 12.1)"
    - script: fastlane scan --scheme "ReadingList" --device "iPad Air (iOS 11.4)"

    - stage: deploy
      script: fastlane deploy
stages:
  - test
  - name: deploy
    if: branch = master