name: ReadingList

options:
  groupSortPosition: top
  usesTabs: false
  indentWith: 4
  bundleIdPrefix: com.andrewbennet
  groupOrdering: 
    - order: [ReadingList, ReadingList_Foundation, ReadingList_UITests, ReadingList_UnitTests, ReadingListWidget, Debug, fastlane]

packages:
  Cosmos:
    url: https://github.com/evgenyneu/Cosmos
    minorVersion: 22.1.0
  SwiftyStoreKit:
    url: https://github.com/bizz84/SwiftyStoreKit
    minorVersion: 0.16.0
  Swifter:
    url: https://github.com/httpswift/swifter
    branch: stable 
  Eureka:
    url: https://github.com/xmartlabs/Eureka.git
    minorVersion: 5.3.0
  ImageRow:
    url: https://github.com/EurekaCommunity/ImageRow
    branch: master
  WhatsNewKit:
    url: https://github.com/SvenTiigi/WhatsNewKit
    minorVersion: 1.3.5
  PersistedPropertyWrapper:
    url: https://github.com/AndrewBennet/PersistedPropertyWrapper.git
    minorVersion: 1.2.0
  Regex:
    url: https://github.com/sharplet/Regex.git
    minorVersion: 2.1.1
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    branch: 6.33-spm-beta
  Promises:
    url: https://github.com/google/promises.git
    minorVersion: 1.2.0
  CHCSVParser:
    url: https://github.com/AndrewBennet/CHCSVParser.git # Fork with SPM support
    branch: master
  SVProgressHUD:
    url: https://github.com/sereivoanyong/SVProgressHUD.git # Fork with SPM support
    branch: master

fileGroups:
  - Debug/
  - fastlane/
  - README.md
  - project.yml

targets:
  ReadingList:
    type: application
    platform: iOS
    deploymentTarget: 12.0
    sources:
      - path: ReadingList
        excludes:
          - Debug
      - path: ReadingListWidget/WidgetKind.swift
    scheme:
      testTargets:
        - ReadingList_UnitTests
        - ReadingList_UITests
    dependencies:
      - sdk: StoreKit.framework
      - target: ReadingList_Foundation
      - target: ReadingListWidget
      - package: Cosmos
      - package: SwiftyStoreKit
      - package: Eureka
      - package: ImageRow
      - package: WhatsNewKit
      - package: PersistedPropertyWrapper
      - package: Regex
      - package: Promises
      - package: CHCSVParser
      - package: SVProgressHUD
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAnalytics
      
    preBuildScripts:
      - name: SwiftLint
        script: |
                if [[ -z $CI ]]; then
                  "/usr/local/bin/swiftlint" --path "${PROJECT_DIR}"
                fi
    postBuildScripts:
      - name: "Copy Debug Files"
        script: |
                BUILD_APP_DIR=${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}
                if [ "$CONFIGURATION" == "Debug" ]; then
                  cp "$SRCROOT/Debug/examplebooks.csv" "$BUILD_APP_DIR/examplebooks.csv"
                  cp "$SRCROOT/Debug/example_barcode.jpg" "$BUILD_APP_DIR/example_barcode.jpg"
                fi
      - name: Run Crashlytics Script
        inputFiles: [$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)]
        script: |
                "${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
    settings:
      base:
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_ENTITLEMENTS: ReadingList/ReadingList.entitlements
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        DEVELOPMENT_TEAM: YPDEV2E775
        PRODUCT_BUNDLE_IDENTIFIER: com.andrewbennet.books
        OTHER_LDFLAGS: -ObjC
      configs:
        Debug:
          # Stupid build errors from Firebase without this. Prevents Debug build being deployed to devices though...
          EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
          PROVISIONING_PROFILE_SPECIFIER: match Development com.andrewbennet.books
          OTHER_SWIFT_FLAGS: $(inherited) "-D" "DEBUG"
        Release:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.andrewbennet.books
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "Apple Distribution: Andrew Bennet (YPDEV2E775)"
          OTHER_SWIFT_FLAGS: $(inherited) "-D" "RELEASE"
    attributes:
      SystemCapabilities:
        com.apple.iCloud:
          enabled: 1
        com.apple.InAppPurchase:
          enabled: 1

  ReadingList_Foundation:
    type: framework
    platform: iOS
    deploymentTarget: 12.0
    sources: [ReadingList_Foundation]

  ReadingList_UnitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 12.0
    sources: [ReadingList_UnitTests]
    dependencies:
      - target: ReadingList

  ReadingList_UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: 12.0
    sources:
      - path: ReadingList_UITests
      - path: ReadingList/Api/GoogleBooksRequest.swift
    dependencies:
      - target: ReadingList
      - package: Swifter
    scheme:
      testTargets:
        - ReadingList_UITests

  ReadingListWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - path: ReadingListWidget
      - path: ReadingList/Data/SharedBookData.swift
      - path: ReadingList/Startup/ProprietaryURLManager.swift
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
      - package: PersistedPropertyWrapper
    postBuildScripts:
      - name: "Copy Debug Files"
        script: |
                BUILD_APP_DIR=${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}
                if [ "$CONFIGURATION" == "Debug" ]; then
                  cp "$SRCROOT/Debug/shared_current-books.json" "$BUILD_APP_DIR/shared_current-books.json"
                  cp "$SRCROOT/Debug/shared_finished-books.json" "$BUILD_APP_DIR/shared_finished-books.json"
                fi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andrewbennet.books.ReadingListWidget
        DEVELOPMENT_TEAM: YPDEV2E775
        CODE_SIGN_ENTITLEMENTS: ReadingListWidget/ReadingListWidget.entitlements
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_STYLE: Manual
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.andrewbennet.books.ReadingListWidget
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "Apple Distribution: Andrew Bennet (YPDEV2E775)"

